language: "node_js"
node_js:
  - 0.6
  - 0.7
branches:
  only:
    - master
notifications:
  webhooks: 
    urls:
      - https://webhooks.nodejitsu.com/1/deploy
    on_success: always
    on_failure: never